"""Initial migration

Revision ID: 678a038bae9b
Revises: 17a8f9d4c8a8
Create Date: 2025-04-25 13:49:15.688642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '678a038bae9b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_results',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('request_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('contextualize', sa.String(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis_results')
    # ### end Alembic commands ###
